[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "npm run production"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

